language: python
sudo: false
python:
  - "2.7"
env:
  global:
    - SPIDERMONKEY_INSTALLATION=${TRAVIS_BUILD_DIR}/spidermonkey/js 
before_install:
  - wget https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-mozilla-aurora/jsshell-linux-x86_64.zip
  - unzip -o jsshell-linux-x86_64.zip -d spidermonkey
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-xunit
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
